AllCops:
  NewCops: enable
  SuggestExtensions: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 2000
  Exclude:
    - 'spec/*.rb'
    - 'spec/**/*.rb'
    - 'Rakefile'
    - '**/*.rake'
    - '*.gemspec'

Metrics/MethodLength:
  Exclude: 
    - 'bin/*'

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'bin/*'

Metrics/ClassLength:
  Exclude:
    - 'bin/*'
